[build-system]
requires = [
    "setuptools>=42.0.2",
    "wheel>=0.29.0"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --cov-config=.coveragerc --cov=cyclonedds --cov-report=xml --import-mode=importlib"
required_plugins = "pytest-cov pytest-mock"
testpaths = "tests"
markers = ["fuzzing: run the fuzzing testsuite."]

# -- Below is the configuration to build wheels using cibuildwheel -- #

[tool.cibuildwheel]

# Skip PyPy (C API incompatible), 32bit systems, and musllinux (glibc/manylinux only)
skip = "pp* *_i686 *musllinux*"

build-verbosity = "1"

before-all = [
    "git clone --branch 0.10.5 --depth 1 https://github.com/eclipse-cyclonedds/cyclonedds.git main",
    "mkdir cyclonedds-build",
    "mkdir build"
]

before-build = [
    "cd build",
    "cmake ../main -DCMAKE_INSTALL_PREFIX=\"../cyclonedds-build\" -DBUILD_DDSPERF=off -DENABLE_SSL=off -DENABLE_SECURITY=off",
    "cmake --build . --config RelWithDebInfo --target install",
    "cd .."
]

# Env variables to signify wheel build and manipulating loading path for cyclone

[tool.cibuildwheel.linux.environment]
STANDALONE_WHEELS = "1"
LD_LIBRARY_PATH = "$(pwd)/cyclonedds-build/lib:$(pwd)/cyclonedds-build/lib64"

# -- End of cibuildwheel configuration -- #
